# Site settings
title: Dennis Yurkevich
email: dennis.yurkevich@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website for hosting of job profile and any projects
  being worked on.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ydennisy.github.io/" # the base hostname & protocol for your site
twitter_username: dennis
github_username:  ydennisy
linkedin_username:dennisyurkevich

# Build settings
markdown: kramdown
